package com.gla.loan_service.enums;

public enum RejectionReason {

    LOW_CREDIT_SCORE,
    HIGH_DEBT_TO_INCOME_RATIO,
    INSUFFICIENT_INCOME,
    EXCESSIVE_EXISTING_LOANS,
    POOR_PAYMENT_HISTORY,
    INCOMPLETE_DOCUMENTS,
    EMPLOYMENT_INSTABILITY,
    LOAN_AMOUNT_TOO_HIGH,
    BLACKLISTED_ACCOUNT,
    OTHER
}